### ISSUE TITLE
Checkpoint 3 Ready for Review

### ISSUE THREAD

**Issue by AliviaK** [AliviaK/recipeSharing#13]
@pawaitemadisoncollege - checkpoint 3 is ready for review!

 Search by username and search all users from the index page both work and return data! Recipe Search, Add Recipe, and Profile pages are built but not completed/functioning yet.

**Comment by pawaitemadisoncollege** [comment]
@AliviaK Great work! I was able to see user data, sign up as a new user and sign in. Your site looks really nice so far - it's good to see some styling on it! Adding bootstrap in sooner than later is a nice touch.  

Re timelog/reflection: Sorry to hear that SendGrid didn't pan out so far :(  I was looking forward to seeing that implementation, but javamail should work as well if you aren't able to get that account opened back up.  You'd think they'd be able to account for development work like you are doing! https://docs.sendgrid.com/ui/account-and-settings/account-under-review
