### ISSUE TITLE
Code Review

### ISSUE THREAD

**Issue by misterToo** [AliviaK/recipeSharing#7]
# Design/Code Review 1
​
## Project: Recipe Sharing
​
### Developer: Alivia Kleinfeldt
​
### Reviewer: Oscar Bedford
​
|Item |Considerations| Comments/Suggestions|
|--------|---------|---|
|||Reviewer comments and suggestions go here. Each item should have *at least* one "kudos" and two suggestions for improvement|
|**Problem Statement**|1. Accurately describes project purpose<br> 2. Is professional and free of typos, slang, etc.<br> 3. Fully explains the problem and the solution<br> 4. Is understandable by the average person| - Extremely detailed problem statement ! <br> - Could possibly boil down to a shorter summary, lotta words <br> -maybe have summary as well as longer description of project  |
|**Design Documentation**|1. Navigation/flow through the application is logical and easy to use. <br>2. The order in which values are displayed are logical and easy to understand/use <br>3. The order in which the form fields entered are logical and easy to understand/use<br>4. All data discussed/documented (problem statement, flow, db design, etc.) is represented on the screens |- What there is extremely professional <br> - needs all the other planned pages diagrammed <br> - since not all pages are diagrammed, not all data is represented  |
|**Data model/Database**|1. Everything on the screens and problem statement/flow is represented in the model <br> 2. There is at least one 1-to-many relationship.<br> 3. The model represents good database design <br>| - multiple one-to-many relationships <br> - based on what you mentioned in the presentation, design is incredibly ambitious, might be difficult to implement effectively <br> -design requires lots of individual ingredients entered into a database   |
|**Code**|1. Proper Maven project structure is used<br> 2. a .gitignore file for IntelliJ Java projects has been implemented <br> 3. There is not any redundant or copy/paste code in the JSPs or classes<br> 4. Classes are appropriately-sized (no monster classes)<br> Property files are used appropriately: no hard-coded values <br> 5. Logging statements are used rather than System.out.println and printStackTrace.<br> 6. There are appropriate unit tests/code coverage.  |-code looks good <br> - has some copy paste equals methods in objects <br>- session factory provider is paula's|

**Comment by pawaitemadisoncollege** [comment]
@misterToo thanks for the review here - it shows that you took some time with the design docs and code base.  

- [x] Github's search feature is a nice way to find those sneaky print statements.
![Screen Shot 2021-10-11 at 6 54 06 PM](https://user-images.githubusercontent.com/13874466/136868664-870ccd07-4a4e-4824-a768-613697897a19.png)
