### ISSUE TITLE
Code Review (Blake)

### ISSUE THREAD

**Issue by Logically2ed** [AliviaK/recipeSharing#8]
# Design/Code Review Kleinfeldt

### Reviewer: Blake McFarlane

|Item |Considerations| Comments/Suggestions|
|--------|---------|---|
|||Reviewer comments and suggestions go here. Each item should have *at least* one "kudos" and two suggestions for improvement|
|**Problem Statement**|1. Accurately describes project purpose<br> 2. Is professional and free of typos, slang, etc.<br> 3. Fully explains the problem and the solution<br> 4. Is understandable by the average person| - Interesting application, this actually implements an idea i had for a while and interested to see how it turns out.<br> - No typos or slang that I can find. <br> - Easy to understand your plan and see your vision.|
|**Design Documentation**|1. Navigation/flow through the application is logical and easy to use. <br>2. The order in which values are displayed are logical and easy to understand/use <br>3. The order in which the form fields entered are logical and easy to understand/use<br>4. All data discussed/documented (problem statement, flow, db design, etc.) is represented on the screens | - Navigation mockup makes sense but i can only find one and it references the ability to make changes to user profiles but no mockup of it. |
|**Data model/Database**|1. Everything on the screens and problem statement/flow is represented in the model <br> 2. There is at least one 1-to-many relationship.<br> 3. The model represents good database design <br>| - The database schema design seems reasonable and I cant think of anythig you could be missing. |
|**Code**|1. Proper Maven project structure is used<br> 2. a .gitignore file for IntelliJ Java projects has been implemented <br> 3. There is not any redundant or copy/paste code in the JSPs or classes<br> 4. Classes are appropriately-sized (no monster classes)<br> Property files are used appropriately: no hard-coded values <br> 5. Logging statements are used rather than System.out.println and printStackTrace.<br> 6. There are appropriate unit tests/code coverage.| - Code is in its infant stages but seems to be well put together in the correct formatting. Code for testing is present and proficient. |

**Comment by pawaitemadisoncollege** [comment]
@Logically2ed - a good way to check for printlns is to search directly in GitHub
![Screen Shot 2021-10-12 at 8 51 06 AM](https://user-images.githubusercontent.com/13874466/136969176-02464efe-9426-46aa-82fd-91618c1bd629.png)
.
