### ISSUE TITLE
Checkpoint 2

### ISSUE THREAD

**Issue by AliviaK** [AliviaK/recipeSharing#9]
@pawaitemadisoncollege - Checkpoint 2 is ready for review!

**Comment by pawaitemadisoncollege** [comment]
@AliviaK You have quite a lot done here already, with three entity-daos unit-tested and the generic dao implemented! Your journal/time log shows excellent regular progress - keep up that great effort!

- [x] Your db design looks well-thought-out! No nitpicks there! 
- [x] I noticed there are some open issues on your repo. As you implement suggestions from the issues in your project, you can check them off to show they've been addressed, and then close the issue when all items are "complete". If there is something you choose not to implement, just add a comment in the issue about that design decision.
